# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clock.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63lock.proto\x12\x05\x63lock\"%\n\x10TimestampMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\t2\x97\x01\n\x0c\x43lockService\x12@\n\x0cGetTimestamp\x12\x17.clock.TimestampMessage\x1a\x17.clock.TimestampMessage\x12\x45\n\x0fStreamTimestamp\x12\x17.clock.TimestampMessage\x1a\x17.clock.TimestampMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clock_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TIMESTAMPMESSAGE']._serialized_start=22
  _globals['_TIMESTAMPMESSAGE']._serialized_end=59
  _globals['_CLOCKSERVICE']._serialized_start=62
  _globals['_CLOCKSERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
