/**
 * @fileoverview gRPC-Web generated client stub for clock
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: clock.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.clock = require('./ClockPb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.clock.ClockServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.clock.ClockServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.clock.TimestampMessage,
 *   !proto.clock.TimestampMessage>}
 */
const methodDescriptor_ClockService_GetTimestamp = new grpc.web.MethodDescriptor(
  '/clock.ClockService/GetTimestamp',
  grpc.web.MethodType.UNARY,
  proto.clock.TimestampMessage,
  proto.clock.TimestampMessage,
  /**
   * @param {!proto.clock.TimestampMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.clock.TimestampMessage.deserializeBinary
);


/**
 * @param {!proto.clock.TimestampMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.clock.TimestampMessage)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.clock.TimestampMessage>|undefined}
 *     The XHR Node Readable Stream
 */
proto.clock.ClockServiceClient.prototype.getTimestamp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/clock.ClockService/GetTimestamp',
      request,
      metadata || {},
      methodDescriptor_ClockService_GetTimestamp,
      callback);
};


/**
 * @param {!proto.clock.TimestampMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.clock.TimestampMessage>}
 *     Promise that resolves to the response
 */
proto.clock.ClockServicePromiseClient.prototype.getTimestamp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/clock.ClockService/GetTimestamp',
      request,
      metadata || {},
      methodDescriptor_ClockService_GetTimestamp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.clock.TimestampMessage,
 *   !proto.clock.TimestampMessage>}
 */
const methodDescriptor_ClockService_StreamTimestamp = new grpc.web.MethodDescriptor(
  '/clock.ClockService/StreamTimestamp',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.clock.TimestampMessage,
  proto.clock.TimestampMessage,
  /**
   * @param {!proto.clock.TimestampMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.clock.TimestampMessage.deserializeBinary
);


/**
 * @param {!proto.clock.TimestampMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.clock.TimestampMessage>}
 *     The XHR Node Readable Stream
 */
proto.clock.ClockServiceClient.prototype.streamTimestamp =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/clock.ClockService/StreamTimestamp',
      request,
      metadata || {},
      methodDescriptor_ClockService_StreamTimestamp);
};


/**
 * @param {!proto.clock.TimestampMessage} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.clock.TimestampMessage>}
 *     The XHR Node Readable Stream
 */
proto.clock.ClockServicePromiseClient.prototype.streamTimestamp =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/clock.ClockService/StreamTimestamp',
      request,
      metadata || {},
      methodDescriptor_ClockService_StreamTimestamp);
};


module.exports = proto.clock;

