# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clock_pb2 as clock__pb2


class ClockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimestamp = channel.unary_unary(
                '/clock.ClockService/GetTimestamp',
                request_serializer=clock__pb2.TimestampMessage.SerializeToString,
                response_deserializer=clock__pb2.TimestampMessage.FromString,
                )
        self.StreamTimestamp = channel.unary_stream(
                '/clock.ClockService/StreamTimestamp',
                request_serializer=clock__pb2.TimestampMessage.SerializeToString,
                response_deserializer=clock__pb2.TimestampMessage.FromString,
                )


class ClockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimestamp,
                    request_deserializer=clock__pb2.TimestampMessage.FromString,
                    response_serializer=clock__pb2.TimestampMessage.SerializeToString,
            ),
            'StreamTimestamp': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTimestamp,
                    request_deserializer=clock__pb2.TimestampMessage.FromString,
                    response_serializer=clock__pb2.TimestampMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clock.ClockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clock.ClockService/GetTimestamp',
            clock__pb2.TimestampMessage.SerializeToString,
            clock__pb2.TimestampMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/clock.ClockService/StreamTimestamp',
            clock__pb2.TimestampMessage.SerializeToString,
            clock__pb2.TimestampMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
